#!/bin/zsh

# Shortcuts
alias dl="cd ~/Downloads"
alias dt="cd ~/iCloud/Desktop"

# Alternatives
alias pip=pip3
alias python=python3

# Combinations
alias burp="sudo -v && npm update -g && brew update && brew upgrade && brew cu -a -y"

# Instant webserver
alias pserver='python3 -m http.server'
